spring:
  datasource:
    username: root
    password: ******
    url: jdbc:mysql://******:3306/******
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
    schema:
      - classpath:SQL/表.sql
      - classpath:SQL/插入.sql
