spring:
  datasource:
    username: root
    password: w20010904
    url: jdbc:mysql://8.210.115.67:3306/Gameshop
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
    schema:
      - classpath:SQL/表.sql
      - classpath:SQL/插入.sql