USE [master]
GO

/****** Object:  Database [Gameshop]    Script Date: 2020/12/22 22:31:12 ******/
CREATE DATABASE [Gameshop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Ganme', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Ganme.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Ganme_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Ganme_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Gameshop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Gameshop] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Gameshop] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Gameshop] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Gameshop] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Gameshop] SET ARITHABORT OFF 
GO

ALTER DATABASE [Gameshop] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Gameshop] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Gameshop] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Gameshop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Gameshop] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Gameshop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Gameshop] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Gameshop] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Gameshop] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Gameshop] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Gameshop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Gameshop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Gameshop] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Gameshop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Gameshop] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Gameshop] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Gameshop] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Gameshop] SET RECOVERY FULL 
GO

ALTER DATABASE [Gameshop] SET  MULTI_USER 
GO

ALTER DATABASE [Gameshop] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Gameshop] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Gameshop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Gameshop] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Gameshop] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Gameshop] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Gameshop] SET  READ_WRITE 
GO;

