CREATE TABLE IF NOT EXISTS `游戏` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `名称` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS 用户(
    id BIGINT NOT NULL AUTO_INCREMENT,
    用户名 VARCHAR(20),
    密码 int(11),
    PRIMARY KEY (id)
);